name: acadion
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ignore: sort_pub_dependencies
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  dio: ^5.4.3
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dismissible_page: ^1.0.2
  envied: ^0.5.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10
  get_it: ^7.7.0
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  ionicons: ^0.2.2
  json_annotation: ^4.9.0
  page_transition: ^2.1.0
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  provider: ^6.1.2
  readmore: ^3.0.0
  retrofit: ^4.1.0
  routefly: ^2.0.2
  skeletonizer: ^1.3.0
  super_sliver_list: ^0.4.1
  url_launcher: ^6.3.0
  very_good_analysis: ^5.1.0
  flutter_force_directed_graph: ^1.0.6
  dotted_border: ^2.1.0
  vector_math: ^2.1.4
  assorted_layout_widgets: ^9.0.1
  sentry_flutter: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ignore: sort_pub_dependencies
  build_runner: ^2.4.11
  envied_generator: ^0.5.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  sentry_dart_plugin: ^2.1.0

dependency_overrides:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

sentry:
  upload_debug_symbols: true
  upload_source_maps: false
  upload_sources: false
  wait_for_processing: false
  commits: auto
  ignore_missing: false
  project: projac
  org: mr-haubrich
